version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
      - image: circleci/postgres:9.6.5-alpine
        name: test-database

    working_directory: ~/tldr
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run: yarn install
      - run: yarn lint
      - run: node_modules/.bin/sequelize db:migrate --config src/config/database.test.json --migrations-path src/database/migrations/
      - run: yarn test && yarn codecov
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
