version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
      - image: circleci/postgres:9.6.5-alpine
        name: test-database

    working_directory: ~/tldr
    steps:
      - checkout
      - restore_cache:
          keys: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
